### ISSUE TITLE
[Question] Pre-built binaries

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [rasta-mouse/Watson#12]
Is there a plan to include pre-built release binaries at any time?

**Comment by rasta-mouse** [comment]
No.  The project isn't particularly hard to build, so I don't see the point in me doing it.

**Comment by ItsIgnacioPortal** [comment]
@rasta-mouse please reconsider publishing pre-built binaries, as it can save people who want to use this project the hassle of downloading and installing the reatively big .NET framework and SDK
