### ISSUE TITLE
Devel on HTB

### ISSUE THREAD

**Issue by HenryEarl** [rasta-mouse/Watson#6]

**Comment by HenryEarl** [comment]
running the x86 on 3.5. Watson complains that Windows version is not supported.

**Comment by rasta-mouse** [comment]
And what version of Windows is Devel running?

**Comment by HenryEarl** [comment]
6.1.7600 N/A Build 7600 - 7 Enterprise

**Comment by rasta-mouse** [comment]
Well the Readme describes which versions are supported, so in what way does this meet the criteria for an Issue?

**Comment by HenryEarl** [comment]
oh, the criteria that I am an idiot and can not read.. sorry for bothering you.

**Comment by HenryEarl** [comment]
User Error

**Comment by fb11** [comment]
How to get to version 1? 2.Version does not support windows 7. Can you add the first release?
https://github.com/rasta-mouse/Watson/releases/tag/1.0

**Comment by rasta-mouse** [comment]
@fb11 just go back through the commit history
https://github.com/rasta-mouse/Watson/tree/486ff207270e4f4cadc94ddebfce1121ae7b5437

**Comment by brentsec** [comment]
Not trying to dig up dead issues, but I felt like opening a new issue was overkill for a related question.

It feels like I'm primarily enumerating on older, internal stuff, and wind up using a compiled binary from the commit you linked. Was that the last commit before support for older builds was taken away?

Might be worth adding a link to the readme with an older commit that works with builds prior to Win10/2016 with the clearly stating that you won't be supporting any problems if people use it.

**Comment by rasta-mouse** [comment]
The reason older versions (e.g 7) were deprecated from the tool was because it was too much to keep on top of.  Even the Windows 10 ecosystem alone is too much, which is why the KBs are always behind.  Ironically when OS's go EoL, they're easier for me to maintain because there are far fewer changes required.  So you never know, some OS's may come back into support in the future.
